import pygame

# Global vars
def init():

    # Grid settings
    global ROWS, COLS, WIDTH, HEIGHT, GRID_HEIGHT, GRID_COL, PROBABILITY, SPEED, SPEED_FACTOR, DELAY
    ROWS = 50
    COLS = 100
    WIDTH = 1401
    HEIGHT = 801
    GRID_HEIGHT = 750
    GRID_COL = (230, 230, 230)
    PROBABILITY = 0.25
    SPEED = 5
    SPEED_FACTOR = 50
    DELAY = 500 - (SPEED * SPEED_FACTOR)


    # Cube settings
    global START_CUBE, END_CUBE, CUBE_HEIGHT, CUBE_WIDTH
    START_CUBE = None
    END_CUBE = None
    CUBE_HEIGHT = GRID_HEIGHT // ROWS
    CUBE_WIDTH = WIDTH // COLS

    # Colors
    global DEFAULT_COLOR, START_COLOR, END_COLOR, WALL_COLOR, VISITED_COLOR, FRONTIER_COLOR, PATH_COLOR
    DEFAULT_COLOR = 'White'
    START_COLOR = 'Blue'
    END_COLOR = 'Orange'
    WALL_COLOR = 'Black'
    VISITED_COLOR = 'Red'
    FRONTIER_COLOR = (255, 175, 255)
    PATH_COLOR = 'Cyan'

    # global button settings
    global RUN_SEL_COLOR, RUN_DE_COLOR, RESET_SEL_COLOR, RESET_DE_COLOR, ALG_CHOICE, ALG_SEL_COLOR, ALG_DE_COLOR, RAND_SEL_COLOR, RAND_DE_COLOR, SPEED_SEL_COLOR, SPEED_DE_COLOR
    RUN_SEL_COLOR = (140,255,140)
    RUN_DE_COLOR = (0, 255, 0) # Darker shade, mouse not hovering on
    RESET_SEL_COLOR = (170, 170, 170)
    RESET_DE_COLOR = (120, 120, 120)
    ALG_CHOICE = 'BFS'
    ALG_SEL_COLOR = (238, 120, 238) #darker pink
    ALG_DE_COLOR = (238, 180, 238) #lighter
    RAND_SEL_COLOR = (170, 170, 170)
    RAND_DE_COLOR = (120, 120, 120)
    SPEED_SEL_COLOR = (255, 255,0)
    SPEED_DE_COLOR = (255, 255, 200)

    # Run Button settings
    global RUN_X, RUN_Y, RUN_WIDTH, RUN_HEIGHT, RUN_COLOR, RUN_BUTTON
    RUN_X = 0
    RUN_Y = 751
    RUN_WIDTH = 200
    RUN_HEIGHT = 50
    RUN_COLOR = RUN_DE_COLOR
    RUN_BUTTON = pygame.Rect(RUN_X, RUN_Y, RUN_WIDTH, RUN_HEIGHT)


    global RESET_X, RESET_Y, RESET_WIDTH, RESET_HEIGHT, RESET_COLOR, RESET_BUTTON
    RESET_X = 250
    RESET_Y = 761
    RESET_WIDTH = 100
    RESET_HEIGHT = 30
    RESET_COLOR = RESET_DE_COLOR
    RESET_BUTTON = pygame.Rect(RESET_X, RESET_Y, RESET_WIDTH, RESET_HEIGHT)

    # BFS Buttons settings
    global BFS_X, BFS_Y, BFS_WIDTH, BFS_HEIGHT, BFS_COLOR, BFS_COLOR, BFS_BUTTON
    BFS_X = (WIDTH//2) - 155
    BFS_Y = 751
    BFS_WIDTH = 150
    BFS_HEIGHT = 50
    BFS_COLOR = ALG_DE_COLOR
    BFS_BUTTON = pygame.Rect(BFS_X, BFS_Y, BFS_WIDTH, BFS_HEIGHT)

    # Astar Button settings
    global ASTAR_X, ASTAR_Y, ASTAR_WIDTH, ASTAR_HEIGHT, ASTAR_COLOR, ASTAR_BUTTON
    ASTAR_X = (WIDTH//2) + 5
    ASTAR_Y = 751
    ASTAR_WIDTH = 150
    ASTAR_HEIGHT = 50
    ASTAR_COLOR = ALG_SEL_COLOR
    ASTAR_BUTTON = pygame.Rect(ASTAR_X, ASTAR_Y, ASTAR_WIDTH, ASTAR_HEIGHT)

    global RAND_WIDTH, RAND_X, RAND_Y, RAND_HEIGHT, RAND_COLOR, RAND_BUTTON
    RAND_WIDTH = 150
    RAND_X = WIDTH - (250+RAND_WIDTH)
    RAND_Y = 761
    RAND_HEIGHT = 30
    RAND_COLOR = RAND_DE_COLOR
    RAND_BUTTON = pygame.Rect(RAND_X, RAND_Y, RAND_WIDTH, RAND_HEIGHT)

    global SBOX_WIDTH, SBOX_X, SBOX_Y, SBOX_HEIGHT, SBOX_COLOR, SBOX_BOX, S_RIGHT
    SBOX_WIDTH = 30
    SBOX_X = WIDTH - (20+SBOX_WIDTH)
    SBOX_Y = 761
    SBOX_HEIGHT = 30
    SBOX_COLOR = (255,255,0)
    SBOX_BOX = pygame.Rect(SBOX_X, SBOX_Y, SBOX_WIDTH, SBOX_HEIGHT)


    global SR_WIDTH, SR_HEIGHT, SR_X, SR_Y, SR_COLOR, S_RIGHT, SL_X, SL_COLOR, S_LEFT
    SR_WIDTH = SBOX_WIDTH//2
    SR_HEIGHT = SBOX_HEIGHT//2
    SR_X = SBOX_X+SBOX_WIDTH+2.5
    SR_Y = SBOX_Y + ((SBOX_HEIGHT - SR_HEIGHT)//2)
    SR_COLOR = SPEED_DE_COLOR
    S_RIGHT = pygame.Rect(SR_X, SR_Y, SR_WIDTH, SR_HEIGHT)

    SL_X = SBOX_X-SR_WIDTH-2.5
    SL_COLOR = SPEED_DE_COLOR
    S_LEFT= pygame.Rect(SL_X, SR_Y, SR_WIDTH, SR_HEIGHT)

    # Text settings
    global RUN_FONT, RESET_FONT, RAND_FONT, SPEED_FONT, SC_FONT, FONT_SEL_COLOR, FONT_DE_COLOR 
    pygame.font.init()
    RUN_FONT = pygame.font.SysFont('Arial', 25)
    RESET_FONT = pygame.font.SysFont('Arial', 15)
    RAND_FONT = pygame.font.SysFont('Arial', 15)
    SPEED_FONT = pygame.font.SysFont('Arial', 15)
    SC_FONT = pygame.font.SysFont('Arial', 15)

    FONT_SEL_COLOR = (85, 85, 85)
    FONT_DE_COLOR = (0,0,0)

    # Font colors
    global RUN_FONT_COLOR, RESET_FONT_COLOR, BFS_FONT_COLOR, ASTAR_FONT_COLOR, RAND_FONT_COLOR, SPEED_FONT_COLOR, SL_FONT_COLOR, SR_FONT_COLOR
    RUN_FONT_COLOR = FONT_DE_COLOR
    RESET_FONT_COLOR = FONT_DE_COLOR
    BFS_FONT_COLOR = FONT_DE_COLOR
    ASTAR_FONT_COLOR = FONT_DE_COLOR
    RAND_FONT_COLOR = FONT_DE_COLOR
    SPEED_FONT_COLOR = FONT_DE_COLOR
    SL_FONT_COLOR = FONT_DE_COLOR
    SR_FONT_COLOR = FONT_DE_COLOR